# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(max_length=100)),
                ('result_code', models.CharField(max_length=100)),
                ('result_desc', models.TextField()),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('refrence_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
