# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request', jsonfield.fields.JSONField()),
            ],
        ),
    ]
