# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesalog',
            old_name='request',
            new_name='referencedata',
        ),
        migrations.AddField(
            model_name='mpesalog',
            name='conversationid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesalog',
            name='originatorconversationid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesalog',
            name='resultcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesalog',
            name='resultdesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesalog',
            name='resulttype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesalog',
            name='transactionid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
