# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesalog',
            old_name='refrence_data',
            new_name='reference_data',
        ),
    ]
