# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0003_mpesalog_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesalog',
            name='referencedata',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpesalog',
            name='result',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
