# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0004_auto_20170814_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesalog',
            name='conversationid',
        ),
        migrations.RemoveField(
            model_name='mpesalog',
            name='originatorconversationid',
        ),
        migrations.RemoveField(
            model_name='mpesalog',
            name='referencedata',
        ),
        migrations.RemoveField(
            model_name='mpesalog',
            name='resultcode',
        ),
        migrations.RemoveField(
            model_name='mpesalog',
            name='resultdesc',
        ),
        migrations.RemoveField(
            model_name='mpesalog',
            name='resulttype',
        ),
        migrations.RemoveField(
            model_name='mpesalog',
            name='transactionid',
        ),
        migrations.AlterField(
            model_name='mpesalog',
            name='result',
            field=jsonfield.fields.JSONField(),
        ),
    ]
