# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('SerialNumber', models.CharField(max_length=15)),
                ('Price', models.FloatField()),
                ('DOA', models.DateField()),
                ('Assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=5)),
                ('Rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='DepClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depreciation.Depreciation'),
        ),
    ]
