# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='assets',
            name='Assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depreciation.User'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
