# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='DepClass',
            new_name='depreciation_id',
        ),
    ]
