# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0002_auto_20170707_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='depreciation_id',
            new_name='depreciation',
        ),
    ]
