# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0002_auto_20170711_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
