# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0003_auto_20170707_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='Assignee',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='DOA',
            new_name='doa',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='SerialNumber',
            new_name='serialnumber',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='Name',
            new_name='title',
        ),
    ]
