# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depreciation', '0004_auto_20170707_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depreciation',
            old_name='Class',
            new_name='dclass',
        ),
        migrations.RenameField(
            model_name='depreciation',
            old_name='Rate',
            new_name='rate',
        ),
    ]
